title: photo-organizer
description: Documentacao oficial do photo-organizer
baseurl: "/photo-organizer"
url: "https://iklav-tech.github.io"
markdown: kramdown
theme: null

defaults:
  - scope:
      path: ""
    values:
      layout: default
